---
service: serverless-node-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  test:
    handler: src/handler.generateRandomName
